Supporting big files
modzy/sdk-javascript pull request #17
Opened 2021-07-01 17:34 UTC by raul-casallas

## Description

With this PR I'm isolating embedded input from file input, so the file handling submit the inputs by using the open and close jobs logic, avoiding server errors to happen

## Related issues

There is not an issue reported but is a well-known fact that is a problem if you want to submit a big list of local files.

## Tests

I add a sample to use this type of input.

## Checklist

- [x] I read the Contributing guide.
- [x] I update the documentation and if the case the README.md file.
- [x] I am willing to follow-up on review comments in a timely manner.

2021-07-01 22:21 UTC, cbatis requested changes

2021-07-01 22:21 UTC, cbatis commented on samples/job_with_file_input_sample.js
> +        // A file input can be a byte array or any file path. This input type fits for any size files.
(...) fits files of any size.

2021-07-02 16:06 UTC, cbatis approved these changes

2021-07-16 14:53 UTC, cbatis requested changes

2021-07-16 14:53 UTC, cbatis commented on src/job-client.js
> +     * @return {Object} a updated job instance
An updated job instance

2021-07-16 14:56 UTC, raul-casallas commented on src/job-client.js
> +     * Call the Modzy API Service that return the jobs features
Done, thanks Caro

2021-07-16 15:01 UTC, cbatis approved these changes

2021-07-16 15:04 UTC, merged